### auth login

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "u1002",
    "password": "changeit"
}

###
@authToken = {{login.response.body.access_token}}

### find all

### create
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "username": "u1003",
    "password": "changeit",
    "role": "USER"
}


### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1002",
    "password": "changeit",
    "role": "USER"
}

### find  all
GET http://localhost:3000/users


###
### Admin Zone
###
# @name loginAdmin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "m1001",
    "password": "changeit"
}

###
@authTokenAdmin = {{loginAdmin.response.body.access_token}}

### create
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "username": "u1004",
    "password": "changeit",
    "role": "USER"
}

###
### Manager Zone
###
# @name loginManager
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "m1001",
    "password": "changeit"
}

###
@authTokenManager = {{loginManager.response.body.access_token}}

### create
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authTokenManager}}